/**
 * Gera o JSON do workflow n8n de RASPAGEM (scraping) usando Serper API e SearXNG em paralelo.
 */
function buildScrapingWorkflow(config) {
  const {
    nicheId,
    nicheName,
    keywords = [],
    contextTerms = ["whatsapp", "contato", "telefone", "wa.me"],
    serperApiKey,
    searxngUrl = "http://searxng:8080/search",
    postgresCredentialId,
    scheduleHours = 6,
  } = config;

  const keywordsEscaped = JSON.stringify(keywords);
  const contextTermsEscaped = JSON.stringify(contextTerms);

  const geraQueriesCode = [
    'const keywords = ' + keywordsEscaped + ';',
    'const contextTerms = ' + contextTermsEscaped + ';',
    'const sites = ["site:instagram.com", "site:facebook.com", ""];',
    'const NICHE_ID = "' + nicheId + '";',
    '',
    'const queries = [];',
    '',
    'for (const kw of keywords) {',
    "  const cleanKw = String(kw).replace(/^[\"']+|[\"']+$/g, '');",
    "  if (!cleanKw) continue;",
    '',
    '  for (const site of sites) {',
    '    for (const ctx of contextTerms) {',
    '      const siteQuery = site ? " " + site : "";',
    '      queries.push({',
    '        q: \'"\' + cleanKw + \'" \' + ctx + siteQuery,',
    '        niche_id: NICHE_ID',
    '      });',
    '    }',
    '  }',
    '}',
    '',
    'return queries.slice(0, 50).map(q => ({ json: q }));'
  ].join('\n');

  const extraiLeadsCode = [
    'const dddsValidos = new Set([11,12,13,14,15,16,17,18,19,21,22,24,27,28,31,32,33,34,35,37,38,41,42,43,44,45,46,47,48,49,51,53,54,55,61,62,63,64,65,66,67,68,69,71,73,74,75,77,79,81,82,83,84,85,86,87,88,89,91,92,93,94,95,96,97,98,99]);',
    '',
    'function extrairWhatsapp(texto) {',
    '  if (!texto) return null;',
    '  const str = String(texto);',
    '  const regex = /(?:\\+?55\\s*)?(?:\\(?([1-9]{2})\\)?\\s*)(?:9\\s*\\d{4}|\\d{4})[\\s.-]?\\d{4}/g;',
    '  const matches = str.match(regex) || [];',
    '  ',
    '  for (const m of matches) {',
    '    const digitos = m.replace(/\\D/g, "");',
    '    let numCompleto = "";',
    '    if (digitos.length === 11) {',
    '      numCompleto = "55" + digitos;',
    '    } else if (digitos.length === 13 && digitos.startsWith("55")) {',
    '      numCompleto = digitos;',
    '    }',
    '    ',
    '    if (numCompleto.length === 13) {',
    '      const ddd = parseInt(numCompleto.substring(2, 4), 10);',
    '      const nonoDigito = numCompleto[4];',
    '      if (dddsValidos.has(ddd) && nonoDigito === "9") {',
    '        return numCompleto;',
    '      }',
    '    }',
    '  }',
    '  return null;',
    '}',
    '',
    'function extrairWaUsername(url) {',
    '  if (!url) return null;',
    '  const match = url.match(/(?:wa\\.me\\/|phone=)(\\d{10,15})/i);',
    '  return match ? match[1] : null;',
    '}',
    '',
    'function sanitizeTexto(str) {',
    "  if (!str) return '';",
    '  return str.replace(/\'/g, "\'\'").trim();',
    '}',
    '',
    'const allItems = $input.all();',
    'const items = [];',
    'const seenUrls = new Set();',
    '',
    'for (const item of allItems) {',
    '  const res = item.json || {};',
    '  if (res.error) continue;',
    '  ',
    '  const currentQuery = res.query || res.searchParameters?.q || res.q || "";',
    "  const nicheId = res.niche_id || '" + nicheId + "';",
    '  ',
    '  const resultsList = [];',
    '  const rawResults = res.results || res.organic || [];',
    '  ',
    '  if (Array.isArray(rawResults)) {',
    '    for (const r of rawResults) {',
    '      resultsList.push({ ',
    '        title: r.title || "", ',
    '        link: r.url || r.link || r.href || "", ',
    '        snippet: r.content || r.snippet || r.body || "" ',
    '      });',
    '    }',
    '  }',
    '  ',
    '  if (Array.isArray(res.places)) {',
    '    for (const p of res.places) {',
    '      resultsList.push({ ',
    '        title: p.title || p.name || "", ',
    '        link: p.website || p.link || p.url || "", ',
    '        snippet: p.address || p.category || "" ',
    '      });',
    '    }',
    '  }',
    '  ',
    '  for (const r of resultsList) {',
    '    const title = r.title;',
    '    const link = r.link;',
    '    const snippet = r.snippet;',
    '    ',
    '    if (!link) continue;',
    '    if (seenUrls.has(link)) continue;',
    '    seenUrls.add(link);',
    '    ',
    '    const textoCompleto = title + " " + snippet + " " + link;',
    '    const whatsapp = extrairWhatsapp(textoCompleto) || extrairWaUsername(link);',
    '    const waUsername = extrairWaUsername(link);',
    '    ',
    '    let whatsappFinal = null;',
    '    let linkWhatsappFinal = null;',
    '    ',
    '    if (whatsapp) {',
    '      whatsappFinal = whatsapp.replace(/\\D/g, "");',
    '      if (whatsappFinal.length === 11) whatsappFinal = "55" + whatsappFinal;',
    '      linkWhatsappFinal = "https://wa.me/" + whatsappFinal;',
    '    }',
    '    ',
    '    const nomePerfil = title ? title.split("|")[0].split("-")[0].trim() : "Desconhecido";',
    '    ',
    '    items.push({',
    '      json: {',
    '        niche_id: nicheId,',
    '        nome_perfil: sanitizeTexto(nomePerfil),',
    '        wa_username: waUsername || null,',
    '        whatsapp: whatsappFinal,',
    '        link_whatsapp: linkWhatsappFinal,',
    '        snippet: sanitizeTexto(snippet.slice(0, 300)),',
    '        fonte_url: link,',
    '        original_query: sanitizeTexto(currentQuery),',
    '        status: whatsappFinal ? "pendente" : "sem_telefone"',
    '      }',
    '    });',
    '  }',
    '}',
    '',
    'if (items.length === 0) {',
    '  return [{',
    '    json: {',
    '      aviso: "Nenhum link valido encontrado nos resultados.",',
    '      exemplo_estrutura: allItems[0]?.json || "Nenhum resultado interno"',
    '    }',
    '  }];',
    '}',
    '',
    'return items;'
  ].join('\n');

  const sanitizaDadosCode = [
    'const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;',
    "const NICHE_ID_FIXO = '" + nicheId + "';",
    'const out = [];',
    '',
    'for (const item of $input.all()) {',
    '  const j = item.json;',
    '  ',
    '  // Se for aviso de "nenhum resultado", passa adiante',
    '  if (j.aviso) {',
    '    out.push({ json: j });',
    '    continue;',
    '  }',
    '  ',
    '  // Corrige niche_id: usa o do item, ou o fixo, ou pula',
    '  let nicheIdFinal = j.niche_id || NICHE_ID_FIXO;',
    '  if (!nicheIdFinal || nicheIdFinal === "undefined" || !UUID_REGEX.test(String(nicheIdFinal))) {',
    '    console.error("niche_id invalido, usando fixo:", nicheIdFinal, "->", NICHE_ID_FIXO);',
    '    nicheIdFinal = NICHE_ID_FIXO;',
    '  }',
    '  ',
    '  // Garante que whatsapp seja null ou string numerica valida',
    '  let whatsapp = j.whatsapp;',
    '  if (whatsapp && (whatsapp === "undefined" || whatsapp === "null")) {',
    '    whatsapp = null;',
    '  }',
    '  ',
    '  // Garante que wa_username seja null ou string valida',
    '  let waUsername = j.wa_username;',
    '  if (waUsername && (waUsername === "undefined" || waUsername === "null")) {',
    '    waUsername = null;',
    '  }',
    '  ',
    '  // Garante que link_whatsapp seja null ou URL valida',
    '  let linkWhatsapp = j.link_whatsapp;',
    '  if (linkWhatsapp && (linkWhatsapp === "undefined" || linkWhatsapp === "null")) {',
    '    linkWhatsapp = null;',
    '  }',
    '  ',
    '  out.push({',
    '    json: {',
    '      niche_id: nicheIdFinal,',
    '      nome_perfil: j.nome_perfil || "Desconhecido",',
    '      wa_username: waUsername,',
    '      whatsapp: whatsapp,',
    '      link_whatsapp: linkWhatsapp,',
    '      snippet: j.snippet || "",',
    '      fonte_url: j.fonte_url || "",',
    '      original_query: j.original_query || "",',
    '      status: j.status || "sem_telefone"',
    '    }',
    '  });',
    '}',
    '',
    'return out;'
  ].join('\n');

  const nodes = [
    {
      id: 'trigger',
      name: 'Schedule Trigger',
      type: 'n8n-nodes-base.scheduleTrigger',
      typeVersion: 1.3,
      position: [0, 0],
      parameters: { rule: { interval: [{ field: 'hours', hoursInterval: scheduleHours }] } },
    },
    {
      id: 'gera_queries',
      name: 'Gera Queries de Busca',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [220, 0],
      parameters: { jsCode: geraQueriesCode },
    },
    {
      id: 'busca_serper',
      name: 'Busca Serper API',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.4,
      position: [440, -120],
      onError: 'continueErrorOutput',
      parameters: {
        method: 'POST',
        url: 'https://google.serper.dev/search',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'X-API-KEY', value: serperApiKey },
            { name: 'Content-Type', value: 'application/json' },
          ],
        },
        sendBody: true,
        specifyBody: 'json',
        jsonBody: '={{ JSON.stringify({ q: $json.q }) }}',
      },
    },
    {
      id: 'busca_searxng',
      name: 'Busca SearXNG',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.4,
      position: [440, 120],
      onError: 'continueErrorOutput',
      parameters: {
        method: 'GET',
        url: searxngUrl,
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'q', value: '={{ $json.q }}' },
            { name: 'format', value: 'json' }
          ]
        },
      },
    },
    {
      id: 'extrai_leads',
      name: 'Extrai e Formata Leads',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [680, 0],
      parameters: { jsCode: extraiLeadsCode },
    },
    {
      id: 'sanitiza_dados',
      name: 'Sanitiza Dados',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [900, 0],
      parameters: { jsCode: sanitizaDadosCode },
    },
    {
      id: 'salva_postgres',
      name: 'Salva Leads no Postgres',
      type: 'n8n-nodes-base.postgres',
      typeVersion: 2.6,
      position: [1120, 0],
      parameters: {
        operation: 'executeQuery',
        query: "INSERT INTO leads (niche_id, nome_perfil, wa_username, whatsapp, link_whatsapp, snippet, fonte_url, original_query, status)\nVALUES ('{{ $json.niche_id }}', '{{ $json.nome_perfil }}', {{ $json.wa_username ? \"'\" + $json.wa_username + \"'\" : 'NULL' }}, {{ $json.whatsapp ? \"'\" + $json.whatsapp + \"'\" : 'NULL' }}, {{ $json.link_whatsapp ? \"'\" + $json.link_whatsapp + \"'\" : 'NULL' }}, '{{ $json.snippet }}', '{{ $json.fonte_url }}', '{{ $json.original_query }}', '{{ $json.status }}')\nON CONFLICT (niche_id, whatsapp) DO NOTHING;",
      },
      credentials: postgresCredentialId ? { postgres: { id: postgresCredentialId, name: 'Postgres account' } } : undefined,
    },
  ];

  const connections = {
    'Schedule Trigger': { main: [[{ node: 'Gera Queries de Busca', type: 'main', index: 0 }]] },
    'Gera Queries de Busca': { 
      main: [
        [
          { node: 'Busca Serper API', type: 'main', index: 0 },
          { node: 'Busca SearXNG', type: 'main', index: 0 }
        ]
      ] 
    },
    'Busca Serper API': { main: [[{ node: 'Extrai e Formata Leads', type: 'main', index: 0 }]] },
    'Busca SearXNG': { main: [[{ node: 'Extrai e Formata Leads', type: 'main', index: 0 }]] },
    'Extrai e Formata Leads': { main: [[{ node: 'Sanitiza Dados', type: 'main', index: 0 }]] },
    'Sanitiza Dados': { main: [[{ node: 'Salva Leads no Postgres', type: 'main', index: 0 }]] },
  };

  return {
    name: '[Maquina de Leads] Raspagem Dual - ' + nicheName,
    nodes,
    connections,
    settings: { executionOrder: 'v1' },
    active: false,
  };
}

module.exports = { buildScrapingWorkflow };
